apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: example
  name: example-pvc
  namespace: example
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  volumeName: example-pv